version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - revive
    - govet
    - staticcheck
  settings:
    revive:
      rules:
        - name: exported
          disabled: true
        - name: var-naming
          disabled: true
