// Package module - module/icons.go
package module

// Nerd Font icon constants for file types and programming languages
// These Unicode characters require a Nerd Font to display correctly
const (
	FileIcon           string = "\uf15b" // FileIcon - default file icon
	FolderIcon         string = "\ue5ff" // FolderIcon - default folder icon
	GoLangIcon         string = "\ue65e" // GoLangIcon - go icon
	MarkdownIcon       string = "\uf48a" // MarkdownIcon - md icon
	GitIcon            string = "\uf1d3" // GitIcon - git icon
	IntellijIcon       string = "\ue7b5" // IntellijIcon - intellij icon
	JSONIcon           string = "\ue60b" // JSONIcon - json icon
	YamlIcon           string = "\ue6a8" // YamlIcon - yaml icon
	DatabaseIcon       string = "\uf1c0" // DatabaseIcon - sql,pls,plb icon
	JavaLangIcon       string = "\ue256" // JavaLangIcon - java, class icon
	CppLangIcon        string = "\ue61d" // CppLangIcon - cpp icon
	CLangIcon          string = "\ue61e" // CLangIcon - c icon
	JavascriptLangIcon string = "\ue74e" // JavascriptLangIcon - javascript icon
	RustLangIcon       string = "\ue68b" // RustLangIcon - rust icon
	PythonLangIcon     string = "\ue606" // PythonLangIcon - python icon
	TypeScriptIcon     string = "\ue628" // TypeScriptIcon - ts, tsx icon
	HTMLIcon           string = "\uf13b" // HTMLIcon - html icon
	CSSIcon            string = "\ue749" // CSSIcon - css icon
	ReactIcon          string = "\ue7ba" // ReactIcon - jsx, tsx icon
	VueIcon            string = "\ue6a0" // VueIcon - vue icon
	DockerIcon         string = "\uf308" // DockerIcon - dockerfile icon
	ShellIcon          string = "\uf489" // ShellIcon - sh, bash icon
	RubyIcon           string = "\ue739" // RubyIcon - rb icon
	PHPIcon            string = "\ue73d" // PHPIcon - php icon
	SwiftIcon          string = "\ue755" // SwiftIcon - swift icon
	KotlinIcon         string = "\ue634" // KotlinIcon - kt icon
	CSharpIcon         string = "\ue648" // CSharpIcon - cs icon
	XMLIcon            string = "\ue619" // XMLIcon - xml icon
	PDFIcon            string = "\uf1c1" // PDFIcon - pdf icon
	ImageIcon          string = "\uf1c5" // ImageIcon - png, jpg, jpeg, gif icon
	VideoIcon          string = "\uf03d" // VideoIcon - mp4, avi, mov icon
	AudioIcon          string = "\uf1c7" // AudioIcon - mp3, wav icon
	ArchiveIcon        string = "\uf410" // ArchiveIcon - zip, tar, gz icon
	TextIcon           string = "\uf0f6" // TextIcon - txt icon
	ConfigIcon         string = "\ue615" // ConfigIcon - conf, cfg, ini icon
	LockIcon           string = "\uf023" // LockIcon - lock icon
	LogIcon            string = "\uf18d" // LogIcon - log icon
	MakefileIcon       string = "\ue673" // MakefileIcon - makefile icon
	NPMIcon            string = "\ue71e" // NPMIcon - package.json icon
	TerraformIcon      string = "\ue69a" // TerraformIcon - tf icon
	ScalaIcon          string = "\ue737" // ScalaIcon - scala icon
	ElixirIcon         string = "\ue62d" // ElixirIcon - ex, exs icon
	HaskellIcon        string = "\ue777" // HaskellIcon - hs icon
	ClojureIcon        string = "\ue76a" // ClojureIcon - clj icon
	DartIcon           string = "\ue798" // DartIcon - dart icon
	RIcon              string = "\uf25d" // RIcon - r, rmd icon
	LuaIcon            string = "\ue620" // LuaIcon - lua icon
	PerlIcon           string = "\ue769" // PerlIcon - pl, pm icon
	LessIcon           string = "\ue758" // LessIcon - less icon
	SvelteIcon         string = "\ue697" // SvelteIcon - svelte icon
	GraphQLIcon        string = "\ue766" // GraphQLIcon - graphql, gql icon
	PrismaIcon         string = "\ue684" // PrismaIcon - prisma icon
	ProtoIcon          string = "\ue60b" // ProtoIcon - proto icon
	LicenseIcon        string = "\uf718" // LicenseIcon - LICENSE icon
	ReadmeIcon         string = "\uf48a" // ReadmeIcon - README icon
	CIIcon             string = "\uf013" // CIIcon - CI/CD files
	VagrantIcon        string = "\uf27d" // VagrantIcon - Vagrantfile icon
	EditorConfigIcon   string = "\ue615" // EditorConfigIcon - editorconfig icon
	ESLintIcon         string = "\ue60c" // ESLintIcon - eslintrc icon
	PrettierIcon       string = "\ue6b4" // PrettierIcon - prettierrc icon
	BabelIcon          string = "\ue74c" // BabelIcon - babelrc icon
	WebpackIcon        string = "\uf6a6" // WebpackIcon - webpack.config icon
	ViteIcon           string = "\ue6a8" // ViteIcon - vite.config icon
	CMakeIcon          string = "\ue615" // CMakeIcon - cmake icon
	GradleIcon         string = "\ue660" // GradleIcon - gradle icon
	MavenIcon          string = "\ue674" // MavenIcon - pom.xml icon
	PipIcon            string = "\ue606" // PipIcon - requirements.txt icon
	PoetryIcon         string = "\ue606" // PoetryIcon - poetry files
	CargoIcon          string = "\ue68b" // CargoIcon - Cargo.toml icon
	SQLiteIcon         string = "\uf1c0" // SQLiteIcon - sqlite, db icon
	BinaryIcon         string = "\uf471" // BinaryIcon - exe, dll, so icon
	WordIcon           string = "\uf1c2" // WordIcon - doc, docx icon
	ExcelIcon          string = "\uf1c3" // ExcelIcon - xls, xlsx icon
	PowerPointIcon     string = "\uf1c4" // PowerPointIcon - ppt, pptx icon
	FontIcon           string = "\uf031" // FontIcon - ttf, otf, woff icon
	CertificateIcon    string = "\uf0a3" // CertificateIcon - cer, crt, p12 icon
	TomlIcon           string = "\ue615" // TomlIcon - toml icon
	NixIcon            string = "\uf313" // NixIcon - nix icon
	WasmIcon           string = "\ue6a1" // WasmIcon - wasm icon
)
